### ISSUE TITLE
Phone Numbers view does not display 'kind' 

### ISSUE THREAD

**Issue by DStringer18** [DStringer18/address_book#9]
As a user, I should be able to view the type, or kind, of phone number in my contact's phone number list.

According to the terminal response, the form does not seem to be sending the data to Active Record: 

```
Started POST "/contacts/1/phone_numbers" for ::1 at 2020-09-25 13:35:08 +0200
Processing by PhoneNumbersController#create as JS
  Parameters: {"authenticity_token"=>"/9hVMTjszqLXREjTC3FHzApvPq8YTfBUh378J/Jtr88FcBhO/PgeoE/f2p/tTyDw/a7WwJwb5UvTWWg+RZCmDA==", "kind"=>"3", "phone_number"=>{"number"=>"123-456-7890", "comment"=>"creating a phone number with kind of 'office' to test."}, "commit"=>"Create Phone number", "contact_id"=>"1"}
  Contact Load (0.6ms)  SELECT "contacts".* FROM "contacts" WHERE "contacts"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/phone_numbers_controller.rb:20:in `create'
   (0.3ms)  BEGIN
  ↳ app/controllers/phone_numbers_controller.rb:21:in `create'
  PhoneNumber Exists? (0.9ms)  SELECT 1 AS one FROM "phone_numbers" WHERE "phone_numbers"."number" = $1 LIMIT $2  [["number", "123-456-7890"], ["LIMIT", 1]]
  ↳ app/controllers/phone_numbers_controller.rb:21:in `create'
  PhoneNumber Create (1.2ms)  INSERT INTO "phone_numbers" ("number", "comment", "contact_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["number", "123-456-7890"], ["comment", "creating a phone number with kind of 'office' to test."], ["contact_id", 1], ["created_at", "2020-09-25 11:35:08.220349"], ["updated_at", "2020-09-25 11:35:08.220349"]]
  ↳ app/controllers/phone_numbers_controller.rb:21:in `create'
   (5.2ms)  COMMIT
  ↳ app/controllers/phone_numbers_controller.rb:21:in `create'
Redirected to http://localhost:3000/contacts/1/phone_numbers
Completed 200 OK in 29ms (ActiveRecord: 8.2ms | Allocations: 5102)
```

**Comment by DStringer18** [comment]
fixed it -- changed 'select_tag' to 'form.select'
